// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaiFoTuPVEsF5uEr61De8wsvepUFrqtc0',
    appId: '1:163071776412:web:e6636434fb3edf52c0bf59',
    messagingSenderId: '163071776412',
    projectId: 'newton-design',
    authDomain: 'newton-design.firebaseapp.com',
    databaseURL: 'https://newton-design-default-rtdb.firebaseio.com',
    storageBucket: 'newton-design.firebasestorage.app',
    measurementId: 'G-JWV6PPDZXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4x6o7FDQPlxYh-E0txG-Yvi1B3piNL7M',
    appId: '1:163071776412:android:2857d935ccabf5bfc0bf59',
    messagingSenderId: '163071776412',
    projectId: 'newton-design',
    databaseURL: 'https://newton-design-default-rtdb.firebaseio.com',
    storageBucket: 'newton-design.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASsx0uep_A75RBgIsD0BSlAzHgioJKkq8',
    appId: '1:163071776412:ios:de3d5d453551e5c2c0bf59',
    messagingSenderId: '163071776412',
    projectId: 'newton-design',
    databaseURL: 'https://newton-design-default-rtdb.firebaseio.com',
    storageBucket: 'newton-design.firebasestorage.app',
    iosClientId: '163071776412-7j8jq0lu9qjt0ns35sukhtp5vru6vl9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.newtonDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASsx0uep_A75RBgIsD0BSlAzHgioJKkq8',
    appId: '1:163071776412:ios:de3d5d453551e5c2c0bf59',
    messagingSenderId: '163071776412',
    projectId: 'newton-design',
    databaseURL: 'https://newton-design-default-rtdb.firebaseio.com',
    storageBucket: 'newton-design.firebasestorage.app',
    iosClientId: '163071776412-7j8jq0lu9qjt0ns35sukhtp5vru6vl9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.newtonDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaiFoTuPVEsF5uEr61De8wsvepUFrqtc0',
    appId: '1:163071776412:web:e6636434fb3edf52c0bf59',
    messagingSenderId: '163071776412',
    projectId: 'newton-design',
    authDomain: 'newton-design.firebaseapp.com',
    databaseURL: 'https://newton-design-default-rtdb.firebaseio.com',
    storageBucket: 'newton-design.firebasestorage.app',
    measurementId: 'G-JWV6PPDZXD',
  );
}
